CREATE TABLE users (
    firstName VARCHAR(255) NOT NULL,
    middleName VARCHAR(255) NOT NULL DEFAULT "",
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(63) NOT NULL DEFAULT "ROLE_USER",
    address VARCHAR(511)
);